#!/bin/bash
# Script 5: Open Source Manifesto Generator
# This script takes user input and generates a personalized manifesto

echo "Answer the following questions to generate your manifesto:"
echo "---------------------------------------------------------"

# Taking user input
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# Get current date
DATE=$(date "+%d %B %Y")

# Output file name
OUTPUT="manifesto_$(whoami).txt"

# Writing manifesto to file
echo "----------------------------------------" > $OUTPUT
echo "Open Source Manifesto" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "----------------------------------------" >> $OUTPUT
echo "" >> $OUTPUT

echo "I believe in the power of open source." >> $OUTPUT
echo "Using tools like $TOOL, I experience true $FREEDOM." >> $OUTPUT
echo "I aim to build and freely share $BUILD with the community." >> $OUTPUT
echo "Together, we can create a more open and collaborative world." >> $OUTPUT

echo "" >> $OUTPUT
echo "Generated by $(whoami)" >> $OUTPUT

# Display output
echo "✅ Manifesto saved to $OUTPUT"
echo ""
cat $OUTPUT
